# Generated by Django 5.0.6 on 2024-07-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apistatisticapp', '0002_alter_event_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='data',
            new_name='date',
        ),
    ]
